apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: test-configmap
spec:
  steps:
  - try:
    - apply:
        file: tests/configmap.yaml
    - assert:
        file: tests/configmap.yaml
